### PR TITLE
Add OPower API

### PR DESCRIPTION
**Pull request by piekstra**

### CODE REVIEW

**Comment by craftyguy** [comment]
seems to work for me! looks like they don't expose hourly usage for the current day or the previous day though :(

```
GET https://pgn.opower.com/ei/edge/apisDataBrowser-v1/cws/utilities/pgn/utilityAccounts/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/reads
{
  "startDate": "2022-07-25",
  "endDate": "2022-07-25",
  "reads": [],
  "siteTimeZoneId": "America/Los_Angeles",
  "units": {
    "consumption": "KWH",
    "demand": null,
    "exported": null,
    "grossConsumption": null,
    "grossGeneration": null,
    "imported": null,
    "reactivePower": null
  },
```

**Comment by piekstra** [comment]
> seems to work for me! looks like they don't expose hourly usage for the current day or the previous day though :(
> 
> ```
> GET https://pgn.opower.com/ei/edge/apisDataBrowser-v1/cws/utilities/pgn/utilityAccounts/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/reads
> {
>   "startDate": "2022-07-25",
>   "endDate": "2022-07-25",
>   "reads": [],
>   "siteTimeZoneId": "America/Los_Angeles",
>   "units": {
>     "consumption": "KWH",
>     "demand": null,
>     "exported": null,
>     "grossConsumption": null,
>     "grossGeneration": null,
>     "imported": null,
>     "reactivePower": null
>   },
> ```

Hmmm. I wonder if that comes from a different endpoint. I'll find out when I wire up the rest! I thought current and previous day usage was available on the site but maybe not.

**Comment by piekstra** [comment]
Working out the response contracts now and then this PR will be ready.

**Comment by craftyguy** [comment]
hmm, ok, the small print here[1] says:

> †Energy usage to date is unavailable for a few days at the end of one billing cycle and the start of the next.

So maybe that's why I was unable to see it... I'm curious if it worked for you though.


1. https://portlandgeneral.com/save-money/save-money-home/energy-tracker-home

**Comment by piekstra** [comment]
> hmm, ok, the small print here[1] says:
> 
> > †Energy usage to date is unavailable for a few days at the end of one billing cycle and the start of the next.
> 
> So maybe that's why I was unable to see it... I'm curious if it worked for you though.
> 
> 1. https://portlandgeneral.com/save-money/save-money-home/energy-tracker-home

Nice find! I wasn't able to get any data for yesterday either 😔 so the docs seem to be accurate.

**Comment by craftyguy** [comment]
ah, well that's a bummer then.

are you following some API documentation for this implementation, or just discovering it as you go?

**Comment by piekstra** [comment]
> ah, well that's a bummer then.
> 
> are you following some API documentation for this implementation, or just discovering it as you go?

They don't have any public-facing docs as far as I've found. Entirely just analyzing their site's source code and monitoring network traffic. Their site is surprisingly well organized 😆

**Comment by craftyguy** [comment]
@piekstra I see.. well done!

**Comment by piekstra** [comment]
closes https://github.com/piekstra/portlandgeneral-api/issues/3

**Pull request merged**
